# Generated by Django 5.1.5 on 2025-02-16 01:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('financeiras', '0001_initial'),
        ('lojas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_status', models.CharField(blank=True, max_length=45, null=True, verbose_name='Status da Proposta')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=45, null=True, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=45, null=True, verbose_name='Modelo')),
                ('ano_fabricacao', models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano de Fabricação')),
                ('ano_modelo', models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano do Modelo')),
                ('placa', models.CharField(blank=True, max_length=8, null=True, verbose_name='Placa')),
                ('renavam', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='RENAVAM inválido. Deve conter exatamente 11 dígitos.', regex='^\\d{11}$')], verbose_name='RENAVAM')),
                ('chassi', models.CharField(blank=True, max_length=17, null=True, verbose_name='Chassi')),
                ('uf', models.CharField(blank=True, default='MS', max_length=2, null=True, verbose_name='UF')),
                ('vl_veiculo', models.FloatField(blank=True, null=True, verbose_name='Valor do Veículo')),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_proposta', models.CharField(max_length=15, unique=True, verbose_name='Número da Proposta')),
                ('vl_financiado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Financiado')),
                ('prazo', models.IntegerField(verbose_name='Prazo (meses)')),
                ('vl_parcela', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da Parcela')),
                ('receita', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Receita')),
                ('dt_proposta', models.DateField(blank=True, null=True, verbose_name='Data da Proposta')),
                ('dt_pagamento', models.DateField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('dt_pagamento_retorno', models.DateField(blank=True, null=True, verbose_name='Data do Pagamento do retorno')),
                ('percentual_financiado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentual Financiado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='clientes.cliente')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='usuarios.filial')),
                ('financeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='financeiras.financeira')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='lojas.loja')),
                ('modalidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiras.modalidade')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='usuarios.operador')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='financeiras.produto')),
                ('segmento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiras.segmento')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propostas', to='lojas.vendedor')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='propostas.statusproposta')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='propostas.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='PagamentoComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Pagamento')),
                ('total_financiado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Financiado')),
                ('total_comissao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Comissão')),
                ('numero_recibo', models.CharField(max_length=20, unique=True, verbose_name='Número do Recibo')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='lojas.loja')),
                ('propostas', models.ManyToManyField(blank=True, related_name='pagamentos', to='propostas.proposta')),
            ],
        ),
    ]
