# Generated by Django 5.1.5 on 2025-02-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='vl_financiado',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Financiado'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='vl_parcela',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da Parcela'),
        ),
    ]
