# Generated by Django 5.1.5 on 2025-02-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusproposta',
            name='ds_status',
            field=models.CharField(blank=True, choices=[('A', 'Aprovada'), ('C', 'Cancelada'), ('E', 'Em Análise'), ('I', 'Integrada/Paga'), ('P', 'Pendente'), ('R', 'Reprovada')], max_length=45, null=True, verbose_name='Status da Proposta'),
        ),
    ]
