# Generated by Django 5.1.5 on 2025-02-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0002_alter_statusproposta_ds_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusproposta',
            name='ds_status',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Status da Proposta'),
        ),
    ]
