# Generated by Django 5.1.5 on 2025-02-13 19:52

import django.db.models.deletion
import usuarios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_filial', models.CharField(blank=True, max_length=45, null=True, verbose_name='Filial')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_perfil', models.CharField(max_length=45, verbose_name='Perfil de Acesso')),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_operador', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome')),
                ('cpf_operador', models.CharField(blank=True, max_length=11, null=True, validators=[usuarios.models.validate_cpf], verbose_name='CPF')),
                ('dt_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('cel_operador', models.CharField(blank=True, max_length=11, null=True, verbose_name='Celular')),
                ('email_operador', models.EmailField(blank=True, max_length=60, null=True, verbose_name='E-Mail')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operadores', to='usuarios.filial')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operador', to=settings.AUTH_USER_MODEL)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil')),
            ],
        ),
    ]
