# Generated by Django 5.1.5 on 2025-02-16 01:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_financeira', models.CharField(max_length=50, verbose_name='Financeira')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_modalidade', models.CharField(blank=True, default='Sem Nome', max_length=50, unique=True, verbose_name='Modalidade')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_departamento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Departamento')),
                ('telefone_fixo', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone Fixo')),
                ('celular', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('financeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='financeiras.financeira')),
            ],
        ),
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_segmento', models.CharField(blank=True, default='Sem Nome', max_length=50, verbose_name='Segmento')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalidades', to='financeiras.modalidade')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(blank=True, max_length=50, verbose_name='Produto')),
                ('comissao_percentual', models.DecimalField(decimal_places=2, default=0, help_text='Percentual de comissão (0 a 100).', max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='A comissão não pode ser inferior a 0%'), django.core.validators.MaxValueValidator(100, message='A comissão não pode ser superior a 100%')], verbose_name='Comissão')),
                ('financeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='financeiras.financeira')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='financeiras.modalidade')),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='financeiras.segmento')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'constraints': [models.UniqueConstraint(fields=('financeira', 'modalidade', 'segmento', 'nome_produto'), name='segmento')],
            },
        ),
    ]
