# Generated by Django 5.1.5 on 2025-02-13 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiras', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_cnpj', models.CharField(max_length=20, unique=True, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=60, verbose_name='Razão Social')),
                ('nm_fantasia', models.CharField(max_length=60, verbose_name='Nome Fantasia')),
                ('dt_constituicao', models.DateField(verbose_name='Data de Constituição')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=60, null=True, verbose_name='Endereço')),
                ('nro', models.CharField(blank=True, max_length=5, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=45, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=45, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=45, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('fone_fixo', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone Fixo')),
                ('celular', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-mail')),
                ('status', models.CharField(choices=[('P', 'Pré-Cadastro'), ('A', 'Aprovada')], default='P', max_length=1, verbose_name='Status')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.filial')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lojas', to='usuarios.operador')),
            ],
        ),
        migrations.CreateModel(
            name='DadosBancarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=3, null=True, verbose_name='Código Banco')),
                ('agencia', models.CharField(blank=True, max_length=5, null=True, verbose_name='Agência')),
                ('conta', models.CharField(blank=True, max_length=11, null=True, verbose_name='Conta')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dadosbancarios', to='lojas.loja')),
            ],
        ),
        migrations.CreateModel(
            name='LojaAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CNPJ', 'CNPJ'), ('CONTRATO', 'Contrato Social'), ('IDENTIFICACAO', 'Identificação dos Sócios'), ('COMPROVANTE_END', 'Comprovante de Endereço'), ('COMPROVANTE_CONTA', 'Comprovante de Conta Corrente'), ('CERTIFICADOS', 'Certificados'), ('DECLARACOES', 'Declarações'), ('FOTOS', 'Fotos')], max_length=50, verbose_name='Tipo de Documento')),
                ('arquivo', models.FileField(upload_to='lojas/anexos/', verbose_name='Arquivo')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='lojas.loja')),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_socio', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome')),
                ('cpf_socio', models.CharField(blank=True, max_length=15, null=True, verbose_name='CPF')),
                ('dt_nascimento_socio', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('celular', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-mail')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socios', to='lojas.loja')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vendedor', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome')),
                ('cpf_vendedor', models.CharField(blank=True, max_length=15, null=True, verbose_name='CPF')),
                ('celular_vendedor', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('email_vendedor', models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-mail')),
                ('chave_pix', models.CharField(blank=True, max_length=60, null=True, verbose_name='Pix')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedores', to='lojas.loja')),
            ],
        ),
        migrations.CreateModel(
            name='LojaFinanceiraAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_acesso', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de Acesso')),
                ('nm_cadastro_fin', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome Cadastrado na Financeira')),
                ('financeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lojas_com_acesso', to='financeiras.financeira')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos_financeiras', to='lojas.loja')),
            ],
            options={
                'unique_together': {('loja', 'financeira')},
            },
        ),
    ]
