# Generated by Django 5.1.5 on 2025-02-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lojaanexo',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='lojas/anexos/'),
        ),
        migrations.AlterField(
            model_name='lojaanexo',
            name='tipo_documento',
            field=models.CharField(max_length=100),
        ),
    ]
