# Generated by Django 5.1.5 on 2025-02-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0002_alter_lojaanexo_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lojaanexo',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='anexos/'),
        ),
    ]
