# Generated by Django 5.1.5 on 2025-02-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0003_alter_lojaanexo_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pré-Cadastro'), ('A', 'Ativa'), ('I', 'Inativa'), ('B', 'Bloqueada')], default='P', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='lojaanexo',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lojaanexo',
            name='tipo_documento',
            field=models.CharField(choices=[('CNPJ', 'CNPJ'), ('CONTRATO', 'Contrato Social'), ('IDENTIFICACAO', 'Identificação dos Sócios'), ('COMPROVANTE_END', 'Comprovante de Endereço'), ('COMPROVANTE_CONTA', 'Comprovante de Conta Corrente'), ('CERTIFICADOS', 'Certificados'), ('DECLARACOES', 'Declarações'), ('FOTOS', 'Fotos'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo de Documento'),
        ),
    ]
