# Generated by Django 5.1.5 on 2025-02-13 19:52

import clientes.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lojas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_cliente', models.CharField(max_length=100, verbose_name='Nome')),
                ('nr_cpf', models.CharField(max_length=14, unique=True, validators=[clientes.models.validate_cpf], verbose_name='CPF')),
                ('dt_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=15, null=True, verbose_name='Sexo')),
                ('nm_mae', models.CharField(blank=True, default='', max_length=100, verbose_name='Nome da Mãe')),
                ('rg_cliente', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
            ],
        ),
        migrations.CreateModel(
            name='ContatoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone_fixo', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone Fixo')),
                ('celular', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='clientes.cliente')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lojas.loja')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.operador')),
            ],
            options={
                'unique_together': {('cliente', 'loja', 'operador', 'celular')},
            },
        ),
        migrations.CreateModel(
            name='EnderecoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=60, null=True, verbose_name='Endereço')),
                ('nro', models.CharField(blank=True, max_length=5, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, default='', max_length=45, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=45, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=45, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='clientes.cliente')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lojas.loja')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.operador')),
            ],
            options={
                'unique_together': {('cliente', 'loja', 'operador', 'cep')},
            },
        ),
        migrations.CreateModel(
            name='ProfissaoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profissao', models.CharField(blank=True, choices=[('Aposentado', 'Aposentado'), ('Assalariado', 'Assalariado'), ('Autônomo', 'Autônomo'), ('Empresário', 'Empresário'), ('Profissional Liberal', 'Profissional Liberal'), ('Servidor Público', 'Servidor Público')], max_length=45, null=True, verbose_name='Profissão')),
                ('cargo', models.CharField(blank=True, max_length=45, null=True, verbose_name='Cargo')),
                ('local_trabalho', models.CharField(blank=True, max_length=45, null=True, verbose_name='Local de Trabalho')),
                ('data_admissao', models.DateField(blank=True, null=True, verbose_name='Data de Admissão')),
                ('renda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Renda')),
                ('fone_lt', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone do Trabalho')),
                ('outras_rendas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Outras Rendas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissoes', to='clientes.cliente')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lojas.loja')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.operador')),
            ],
            options={
                'unique_together': {('cliente', 'loja', 'operador', 'profissao')},
            },
        ),
    ]
